# -*- coding: utf-8 -*-
"""Project3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTSwGkREzOL4Dn-qTKZ3DvU8o0AgEtrI
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""### 1. Loading the Dataset"""

# Load the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
wine_data = pd.read_csv(url, delimiter=';')

# Display the first few rows
wine_data.head()

"""2. Understanding the Data"""

# Check for missing values
print(wine_data.isnull().sum())

"""### 3. Data Exploration/Visualization"""

# Summary statistics
print(wine_data.describe())

# Histograms for each feature
wine_data.hist(bins=20, figsize=(20, 15))
plt.show()

# Correlation matrix
corr_matrix = wine_data.corr()
print(corr_matrix)

# Correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.show()

"""### 4. More Exploratory Data Analysis"""

# Boxplots for each feature
wine_data.plot(kind='box', subplots=True, layout=(4, 4), figsize=(20, 20), sharex=False, sharey=False)
plt.show()

# Pairplots to visualize relationships
sns.pairplot(wine_data)
plt.show()